# Data Analysis Level 2

## **Filtering in Pandas DataFrame**

Filtering is one of the core operations when working with Pandas DataFrames. It allows you to select rows based on specific conditions, making data analysis more efficient.

**Filtering Rows Based on a Single Condition**

You can filter rows by applying a condition to a column.

### **Steps:**
1. Use a boolean condition to filter rows.
2. Apply the condition using comparison operators like `==`, `!=`, `<`, `>`, `<=`, or `>=`.
3. Pass the condition to the DataFrame inside square brackets.

In [ ]:
import pandas as pd
df = pd.read_csv("titanic3.csv")
df.head(5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
# Filter passengers who are female
female_passengers = df[df['Sex'] == 'female']
female_passengers.head()

In [ ]:
# Filter passengers who survived
survived_passengers = df[df['Survived'] == 1]
survived_passengers.head()

## Exercise
Filter passengers older than 50 years

## **Filtering Rows Based on Multiple Conditions**

You can combine multiple conditions when filtering rows in a Pandas DataFrame using:

- **AND (`&`)**: Rows must meet **all conditions**.
- **OR (`|`)**: Rows must meet **at least one condition**.
- **NOT (`~`)**: Negates the condition (excludes rows meeting the condition).

## **Filtering with AND (`&`)**

In [ ]:
filtered_df = df[(df['Sex'] == 'female') & (df['Age'] > 30)]
filtered_df[['Name', 'Sex', 'Age']].head()

## **Filtering with OR (|)**

In [ ]:
# Male passengers or those who survived
filtered_df = df[(df['Sex'] == 'male') | (df['Survived'] == 1)]
filtered_df[['Name', 'Sex', 'Survived']].head()

## **Filtering with NOT (~)**

In [ ]:
# Passengers who are not male
filtered_df = df[~(df['Sex'] == 'male')]
filtered_df[['Name', 'Sex']].head()

## Combining Multiple Conditions

In [ ]:
# Female passengers older than 30 who embarked at port 'C'
filtered_df = df[(df['Sex'] == 'female') & (df['Age'] > 30) & (df['Embarked'] == 'C')]
filtered_df[['Name', 'Sex', 'Age', 'Embarked']].head()

## Exercise
1. Write a filter to find all passengers who Are male, and Have an Age greater than 40.<br>
Display only the columns 'Name', 'Sex', and 'Age'.
2. Write a filter to find passengers who's Embarked at port "S", or Paid a Fare greater than 50. <br>
Display only the columns 'Name', 'Embarked', and 'Fare'.
3. Write a filter to find all passengers who are not female. <br>
Display only the columns 'Name', 'Sex', and 'Age'.
4. Write a filter to find passengers who meet all the following conditions:
  - Are female,
  - Have an Age greater than 35, and
  - Paid a Fare less than 100.<br>
Display only the columns 'Name', 'Sex', 'Age', and 'Fare'.
5. Write a filter to find passengers who:
  - Survived, and
  - Either:
    - Embarked at port "C", or
    - Paid a Fare greater than 50.<br>
Display only the columns 'Name', 'Survived', 'Embarked', and 'Fare'.

# Replacing Values
replace is a tool we use to replace values that is simple and yet has the powerful ability to accept regular expressions.

In [ ]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
df['sex'].replace({"female" : "F" , "male" : "M"})

0         F
1         M
2         F
3         M
4         F
       ...
1305      F
1306      M
1307      M
1308      M
1309    NaN
Name: sex, Length: 1310, dtype: object

In [ ]:
import numpy as np
df['cabin'].replace({np.nan : "-"})

0            B5
1       C22 C26
2       C22 C26
3       C22 C26
4       C22 C26
         ...
1305        NaN
1306        NaN
1307        NaN
1308        NaN
1309        NaN
Name: cabin, Length: 1310, dtype: object

In [ ]:
df['sex'] = df['sex'].replace({"male":"M" , "female" : "F"})

In [ ]:
df['sex'] = df['sex'].replace(["M" , "F"] , ["MALE" , "FEMALE"]) # dict(zip([] , []))

In [ ]:
df.rename({"pclass" : "Passenger Class"}, axis = 1, inplace = True) # index and columns

## Exercise
In the 'Embarked' column:
  - Replace 'S' with 'Southampton'.
  - Replace 'C' with 'Cherbourg'.
  - Replace 'Q' with 'Queenstown'.<br>
Display the updated DataFrame.

## Pandas Groupby -

The `groupby` function in Pandas is used to group data based on one or more columns. It allows you to perform aggregate operations, such as calculating sums, averages, counts, or other summary statistics for each group.

### 1 . Splitting criteria - single, multi level split
### 2 . Aggregation - takes numerical data and applies aggregation functions to them  - dict

In [ ]:
df.head()

,Passenger Class,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
# what is the average age by Gender ?
# Is there a significant difference between fare prices of survived individuals and not survived ?

In [ ]:
df[df['sex']=='female']['age'].mean()
df[df['sex']=='male']['age'].mean()

# Splitting  - sex columns
# Consideration - age
# Aggregation Function - mean


# df.groupby(<SPLIT>).agg({<consideration> : <aggregation function>})

df.groupby("sex").agg({"age" : "mean"})

              age
sex
female  28.687071
male    30.585233

In [ ]:
df['survived'] = df['survived'].replace({0 : "No" , 1 : "Yes"})

In [ ]:
df['count'] = 1
df.groupby(["sex","survived"]).agg({"primary" : "count"}) # Count - is a non null count

                 count
sex    survived
female No          127
       Yes         339
male   No          682
       Yes         161

In [ ]:
df.groupby(["sex" , "survived"]).agg({"age" : ["mean","max"] , "fare" : "mean"}).round(0).astype(int)

                 age     fare
                mean max mean
sex    survived
female No         25  63   22
       Yes        30  76   55
male   No         32  74   24
       Yes        27  80   37

## Exercise

1. Find the average cost of tickets by passenger class<br>
  1.1 - By Gender, By Survival - find the min and maximum age of passengers
2. Find the passenger who paid the maximum cost for a ticket in both males and females
3. Find the average survival ratio by home destination
4. By gender, by survival - find average fare paid

## Dropping Duplicate Rows

In Pandas, duplicate rows can be removed easily using the `.drop_duplicates()` method. This is particularly useful for cleaning datasets.

Use drop_duplicates, but be mindful of the parameters:

In [ ]:
# Duplicate data should be allowed to exist

In [ ]:
# Dataset - 10 Million users - 1st thing you will do ?

# Quality Check
# 1. Duplicates
# 2. Null values - usage statistics for 9 M - 7 M , 2M less
# 3. Data Cleaning - convert data to form it is in to the form you want it in
# 4. Analysis and usage for modelling

In [ ]:
df = df.drop(1309)

In [ ]:
df.drop("cabin", axis = 1, inplace = True)

In [ ]:
len(df.drop_duplicates()) / len(df)

1.0

In [ ]:
df.loc[1309] = df.loc[1308]

In [ ]:
len(df.drop_duplicates()) / len(df)

0.999236641221374

In [ ]:
len(df) - len(df.drop_duplicates())

1

In [ ]:
cols_list = list(df.columns)

In [ ]:
cols_list.remove("count")

In [ ]:
len(df.drop_duplicates()) / len(df)

1.0

In [ ]:
len(df.drop_duplicates()) / len(df)

0.9992372234935164

In [ ]:
df[ df.duplicated() ] # From Pranavi

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1309,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0,0.0,0.0,315082,7.875,NaN,S,NaN,NaN,NaN

In [ ]:
# Primary Keys - composite keys - that can never be duplicated - Transaction ID
# Customer ID, Transaction ID , Date

In [ ]:
df.drop(1309, inplace = True)

In [ ]:
df.drop_duplicates(subset = ['survived', 'sex'])

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,survived_categorical,COUNT
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",FEMALE,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",ALIVE,1
1,1.0,1.0,"Allison, Master. Hudson Trevor",MALE,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",ALIVE,1
2,1.0,0.0,"Allison, Miss. Helen Loraine",FEMALE,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",DEAD,1
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",MALE,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",DEAD,1

In [ ]:
# Drop duplicates, show first two rows of output
df.drop_duplicates(inplace = True)

In [ ]:
# count of Duplicate Values
len(df) - len(df.drop_duplicates())

0

In [ ]:
# Show number of rows
print("Number Of Rows In The Original DataFrame:", len(df))
print("Number Of Rows After Deduping:", len(df.drop_duplicates()))

Number Of Rows In The Original DataFrame: 1310
Number Of Rows After Deduping: 1310

The solution didn’t actually drop any rows. The reason is because drop_duplicates defaults to only dropping rows that match perfectly across all columns. Under this condition, every row in our DataFrame, data frame, is actually unique. However, often we want to consider only a subset of columns to check for duplicate rows. We can accomplish this using the subset parameter:

In [ ]:
# Drop duplicates
df.drop_duplicates(subset = ['cabin','sex','age'])

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1263,3.0,0.0,"van Billiard, Master. Walter John",male,11.5000,1.0,1.0,A/5. 851,14.5000,NaN,S,NaN,1.0,NaN
1301,3.0,0.0,"Youseff, Mr. Gerious",male,45.5000,0.0,0.0,2628,7.2250,NaN,C,NaN,312.0,NaN
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In this statement, we told drop_duplicates to only consider any two rows with the same value for Sex to be duplicates and to drop them. Now we are left with a DataFrame of only two rows: one man and one woman. You might be asking why drop_duplicates decided to keep these two rows instead of two different rows. The answer is that drop_duplicates defaults to keeping the first occurrence of a duplicated row and dropping the rest. We can control this behavior using the keep parameter:

In [ ]:
# subset_cols_for_duplicates = list(df.columns).remove('timestamp')

In [ ]:
# Drop duplicates
df.drop_duplicates(subset = subset_cols_for_duplicates, keep = 'last')

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,Fare
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",F,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",169.07
1,1.0,1.0,AllisonMasterHudsonTrevor,M,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",121.24

**Note**: A related method is duplicated, which returns a boolean series denoting if a row is a duplicate or not. This is a good option if you don’t want to simply drop duplicates.

# Pivot table
**What is pivot Table**<br>
A pivot table is a table of statistics that summarizes the data of a more extensive table. In practical terms, a pivot table calculates a statistic on a breakdown of values. For the first column, it displays values as rows and for the second column as columns.

In [ ]:
df = pd.read_csv("listings.csv")

df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365
3,71609,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355

In [ ]:
# df.groupby(['neighbourhood_group', 'room_type']).agg({"price" : "mean"})
pd.set_option("display.max_columns", 1000)
df.pivot_table(index = "neighbourhood_group" , columns = "room_type",
              values = "price" , aggfunc = "mean")

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group
Central Region            224.581862    114.380117    59.198276
East Region               209.358779    117.234973   187.090909
North Region              188.433962     81.992958   107.666667
North-East Region         191.671875     79.878676    55.000000
West Region               334.178082    117.825397   106.125000

In [ ]:
df.pivot_table(index="embarked", columns="survived", values="fare", aggfunc='mean')

survived        0.0        1.0
embarked
C         40.255592  80.000807
Q         11.615349  13.833998
S         21.546160  39.183470

**Can I calculate multiple statistics at the same time?** <br>

The argument aggfunc of pivot_table function takes a list of functions. Let’s try it with sum and mean.

In [ ]:
df.pivot_table(index="embarked", columns="survived", values="fare", aggfunc=['sum','mean'])

                 sum                   mean
survived         0.0         1.0        0.0        1.0
embarked
C          4830.6711  12000.1211  40.255592  80.000807
Q           917.6126    608.6959  11.615349  13.833998
S         13121.6114  11911.7748  21.546160  39.183470

## Exercise
Create a pivot table to calculate the survival rate ('Survived') for each combination of:
  - 'Pclass'
  - 'Sex'
  - 'Embarked'<br>
Display the survival rate as percentages.

# Looping Over a Column

In [ ]:
for i in range(len(df)):

    df.loc[i,'price'] = df.loc[i,'price']*1.1

In [ ]:
# Price > 80 ignore, <80 - add 10 price units

for i in range(len(df)): # df.index
    price_val = df.loc[i,'price']

    if price_val < 80:
        df.loc[i,'price'] = df.loc[i,'price'] + 10

In [ ]:
df.drop(1309, inplace = True)

In [ ]:
df = pd.read_csv("titanic3.csv")
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
%%timeit

for i in range(len(df['name'])):

    name = df.loc[i,'name']
    try:
        if ("Mr." in name) or ("Mrs." in name):
            df.loc[i,'Marital_Status'] = "Married"
        elif ("Master." in name) or ("Miss." in name):
            df.loc[i,'Marital_Status'] = "Single"
        else:
            df.loc[i,'Marital_Status'] = "Unknown"
    except:
        pass

396 ms ± 7.53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
def marital_status_finder(name):

    if ("Mr." in name) or ("Mrs." in name):
        return "Married"
    elif ("Master." in name) or ("Miss." in name):
        return "Single"
    else:
        return "Unknown"

In [ ]:
df.drop(1309, inplace = True)

In [ ]:
%%timeit
df['name'].apply(marital_status_finder)

255 µs ± 7.05 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

# Applying a Function Over All Elements in a Column
apply is a great way to do data cleaning and wrangling. It is common to write a function to perform some useful operation (separate first and last names, convert strings
to floats, etc.) and then map that function to every element in a column

In [ ]:
def marital_status(name):
    name = name.lower()
    name = " "+name
    if (" mr " in name) or (" mr." in name) or ("mrs." in name):
        return "Married"
    elif ("master." in name) or ("miss." in name):
        return "Single"
    else:
        return "Unknown"

In [ ]:
df['name'].apply(marital_status)

0        Single
1        Single
2        Single
3       Married
4       Married
         ...
1304     Single
1305     Single
1306    Married
1307    Married
1308    Married
Name: name, Length: 1309, dtype: object

In [ ]:
%%timeit
df['Marital_Status'] = df['name'].apply(marital_status)

335 µs ± 7.51 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [ ]:
dataframe=pd.read_csv("data/titanic3.csv")
#dataframe.info()

# Create function
def uppercase(x):
    return str(x).upper()

# Apply function, show two rows
dataframe['sex'].apply(uppercase)

In [ ]:
dataframe['sex'] = dataframe['sex'].apply(uppercase)

In [ ]:
dataframe.head(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",FEMALE,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",MALE,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
dataframe.loc[1,'sex']

'MALE'

In [ ]:
%%timeit

for i in range(len(dataframe)):
    dataframe.loc[i,'sex'] = dataframe.loc[i,'sex'].upper()

616 ms ± 43.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
%%timeit
dataframe['sex'].apply(uppercase)

606 µs ± 21 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

# Applying a Function to Groups
apply is particularly useful when you want to
apply a function to groups. By combining groupby and apply we can calculate custom statistics or apply any function to each group separately.

In [ ]:
# Lambda Function -
# I'm not going to define the name and other details of the function
# Create and use it on the fly

In [ ]:
def adder(a,b ):
    return a+b

In [ ]:
lambda a,b : a+b if a<0 else a-b # Simple, anonymous, one liner functions to use on the fly

In [ ]:
f(-1, 5)

4

In [ ]:
f(10,5)

5

In [ ]:
# dataframe=pd.read_csv("data/titanic3.csv")

# Group rows, apply function to groups
# df.groupby("sex").agg({"age":"mean"})

df.groupby('sex').apply(lambda x: x['age'].mean())

sex
female    28.687071
male      30.585233
dtype: float64

In [ ]:
df.groupby('sex').apply(lambda x: x.count()) # Count - adds 1 for EXISTING value, 0 for Missing values

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,Marital_Status
sex,,,,,,,,,,,,,,,
female,466,466,466,466,388,466,466,466,466,141,464,319,8,288,466
male,843,843,843,843,658,843,843,843,842,154,843,167,113,457,843

# Concatenating DataFrames
The informal definition
of concatenate is to glue two objects together. In the solution we glued together two small DataFrames using the axis parameter to indicate whether we wanted to stack
the two DataFrames on top of each other or place them side by side.

In [ ]:
# file - .csv (.read_csv , .read_excel) file - get the dataframe
# data is generated by code - Python datatype - dict, list, tuple set etc.

In [ ]:
# Create DataFrame
data_a = {'id': ['1', '2', '3'],
          'first': ['Alex', 'Amy', 'Allen'],
          'last': ['Anderson', 'Ackerman', 'Ali']}
dataframe_a = pd.DataFrame(data_a, columns = ['id', 'first', 'last'])

# Create DataFrame
data_b = {'id': ['4', '5', '6'],
          'first': ['Billy', 'Brian', 'Bran'],
          'last': ['Bonder', 'Black', 'Balwner']}
dataframe_b = pd.DataFrame(data_b, columns = ['id', 'first', 'last'])

In [ ]:
dataframe_a

  id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali

In [ ]:
dataframe_b

  id  first     last
0  4  Billy   Bonder
1  5  Brian    Black
2  6   Bran  Balwner

In [ ]:
concat_df = pd.concat([dataframe_a , dataframe_b.drop(columns = ["last"])], axis = 0).reset_index(drop = True) # default - Vertical
concat_df

  id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
3  4  Billy       NaN
4  5  Brian       NaN
5  6   Bran       NaN

In [ ]:
# Create row
row = pd.Series([10,  'Chillon','Chris'], index=['id', 'last','first'])
# Append row
dataframe_a.append(row, ignore_index=True)

   id  first      last
0   1   Alex  Anderson
1   2    Amy  Ackerman
2   3  Allen       Ali
3  10  Chris   Chillon

In [ ]:
# temp = pd.read_csv("listings.csv")
# pd.to_datetime(temp['last_review'])

# Merging DataFrames
Oftentimes, the data we need to use is complex; it doesn’t always come in one piece. Instead in the real world, we’re usually faced with disparate datasets, from multiple database queries or files. To get all that data into one place, we can load each data query or data file into pandas as individual DataFrames and then merge them
together into a single DataFrame.

This process might be familiar to anyone who has used SQL, a popular language for doing merging operations (called joins). While the exact parameters used by pandas
will be different, they follow the same general patterns used by other software lan‐
guages and tools.

There are three aspects to specify with any merge operation. First, we have to specify the two DataFrames we want to merge together. In the solution we named them dataframe_employees and dataframe_sales. Second, we have to specify the name(s) of the columns to merge on—that is, the columns whose values are shared between the
two DataFrames. For example, in our solution both DataFrames have a column named employee_id. To merge the two DataFrames we will match up the values in each DataFrame’s employee_id column with each other. If these two columns use the same name, we can use the on parameter. However, if they have different names we
can use left_on and right_on.

What is the left and right DataFrame? The simple answer is that the left DataFrame is the first one we specified in merge and the right DataFrame is the second one. This
language comes up again in the next sets of parameters we will need.

The last aspect, and most difficult for some people to grasp, is the type of merge operation we want to conduct. This is specified by the how parameter. merge supports the four main types of joins:

**Inner Join**: Return only the rows that match in both DataFrames (e.g., return any row with an employee_id value appearing in both dataframe_employees and data
frame_sales).


**Outer Join**: Return all rows in both DataFrames. If a row exists in one DataFrame but not in the other DataFrame, fill NaN values for the missing values (e.g., return all rows in both employee_id and dataframe_sales).

**Left Join**: Return all rows from the left DataFrame but only rows from the right DataFrame that matched with the left DataFrame. Fill NaN values for the missing values (e.g., return all rows from dataframe_employees but only rows from data frame_sales that have a value for employee_id that appears in dataframe_employees).

**Right Join**: Return all rows from the right DataFrame but only rows from the left DataFrame that matched with the right DataFrame. Fill NaN values for the missing values (e.g., return all rows from dataframe_sales but only rows from data frame_employees that have a value for employee_id that appears in dataframe_sales).

In [ ]:
# MERGE

# Ideas we need to keep in mind -

# How many tables can we merge at once ?
# We need to provide the column on the basis of which we merge -
# If the column names are different in the two tables - then we have to provide the 2 column names as well
# The joining criteria - how = inner, outer, left, right

In [ ]:
# Create DataFrame
employee_data = {'employee_id': ['1', '2', '3', '4'],
                 'name': ['Amy Jones', 'Allen Keys', 'Alice Bees','Tim Horton']}
dataframe_employees = pd.DataFrame(employee_data, columns = ['employee_id','name'])

# Create DataFrame
sales_data = {'emp_id': ['3', '4', '5', '6'],
              'total_sales': [23456, 2512, 2345, 1455]}
dataframe_sales = pd.DataFrame(sales_data, columns = ['emp_id','total_sales'])

In [ ]:
dataframe_employees

  employee_id        name
0           1   Amy Jones
1           2  Allen Keys
2           3  Alice Bees
3           4  Tim Horton

In [ ]:
dataframe_sales

  emp_id  total_sales
0      3        23456
1      4         2512
2      5         2345
3      6         1455

In [ ]:
pd.merge(dataframe_employees ,dataframe_sales,
         left_on = "employee_id" , # same column - on = "emp_id"
         right_on = "emp_id",
         how = "outer" ) # left, right, inner, outer

  employee_id        name emp_id  total_sales
0           1   Amy Jones    NaN          NaN
1           2  Allen Keys    NaN          NaN
2           3  Alice Bees      3      23456.0
3           4  Tim Horton      4       2512.0
4         NaN         NaN      5       2345.0
5         NaN         NaN      6       1455.0

In [ ]:
# merged_df[pd.notnull(merged_df['total_sales'])]

## Exercise

### **Dataset Setup**

Use the following code to create sample DataFrames for the exercises:

```python
# DataFrame 1: Titanic Passenger Information (Sample)
data1 = {
    'PassengerId': [1, 2, 3, 4],
    'Name': ['John', 'Alice', 'Bob', 'Mary'],
    'Pclass': [1, 2, 3, 1]
}
df1 = pd.DataFrame(data1)

# DataFrame 2: Survival Information
data2 = {
    'PassengerId': [1, 2, 3, 4],
    'Survived': [1, 0, 1, 1],
    'Age': [22, 28, 34, 45]
}
df2 = pd.DataFrame(data2)

# DataFrame 3: Embarkation Information
data3 = {
    'PassengerId': [3, 4, 5, 6],
    'Embarked': ['S', 'C', 'Q', 'S'],
    'Fare': [7.25, 71.83, 8.05, 15.5]
}
df3 = pd.DataFrame(data3)

1. Merge df1 and df2 on 'PassengerId' using an inner join.<br>
Display the resulting DataFrame.
2. Merge df2 and df3 on 'PassengerId' using a left join.<br>
Display the resulting DataFrame.
3. Concatenate df1 and df3 vertically (along rows).<br>
Reset the index after concatenation.
Display the resulting DataFrame.
4. Concatenate df1 and df2 horizontally (along columns).<br>
Display the resulting DataFrame.
5. Merge all three DataFrames (df1, df2, and df3) into a single DataFrame:
  - Use an outer join on 'PassengerId'.
  - Display the resulting DataFrame.