### Let's learn the Real Magic ! <br> One of the most important Libraries in Python for Data Science <br>
# Pandas

Pandas is an open-source Python Library providing high-performance data manipulation and analysis tool using its powerful data structures. The name Pandas is derived from the word Panel Data – an Econometrics from Multidimensional data.

In 2008, developer Was McKinney started developing pandas when in need of high performance, flexible tool for analysis of data.

Prior to Pandas, Python was majorly used for data munging and preparation. It had very little contribution towards data analysis. Pandas solved this problem. Using Pandas, we can accomplish five typical steps in the processing and analysis of data, regardless of the origin of data — load, prepare, manipulate, model, and analyze.

Python with Pandas is used in a wide range of fields including academic and commercial domains including finance, economics, Statistics, analytics, etc.
Key Features of Pandas
```
    - Fast and efficient DataFrame object with default and customized indexing.
    - Tools for loading data into in-memory data objects from different file formats.
    - Data alignment and integrated handling of missing data.
    - Reshaping and pivoting of date sets.
    - Label-based slicing, indexing and subsetting of large data sets.
    - Columns from a data structure can be deleted or inserted.
    - Group by data for aggregation and transformations.
    - High performance merging and joining of data.

In [ ]:
import pandas as pd # Work directly - pandas comes pre installed with the anaconda package

In [ ]:
import imblearn as imb  # does not exist in your system -> Install the library
# %pip install imblearn
# import imblearn as imb

In [ ]:
print('Pandas Version : ' , pd.__version__)

Pandas Version :  1.5.0

## Python Pandas - DataFrame

A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.
Features of DataFrame

    Potentially columns are of different types
    Size – Mutable
    Labeled axes (rows and columns)
    Can Perform Arithmetic operations on rows and columns

### Structure

Let us assume that we are creating a data frame with student’s data.
Structure Table

You can think of it as an SQL table or a spreadsheet data representation.
pandas.DataFrame

A pandas DataFrame can be created using the following constructor −

pandas.DataFrame( data, index, columns, dtype, copy)

### Create DataFrame
A pandas DataFrame can be created using various inputs like −

    Lists
    dict
    Series
    Numpy ndarrays
    Another DataFrame

In the subsequent sections of this chapter, we will see how to create a DataFrame using these inputs.
Create an Empty DataFrame

A basic DataFrame, which can be created is an Empty Dataframe.

In [1]:
import pandas as pd

# 1D List
data = [10, 20, 30, 40]
df = pd.DataFrame(data, columns=['Values'])
print(df)

   Values
0      10
1      20
2      30
3      40

In [2]:
# 2D List
data_2d = [[1, 'Alice'], [2, 'Bob'], [3, 'Charlie']]
df_2d = pd.DataFrame(data_2d, columns=['ID', 'Name'])
print(df_2d)

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [3]:
# Dictionary
data_dict = {
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}
df_dict = pd.DataFrame(data_dict)
print(df_dict)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

## Exercise
Create a dictionary with the following data:
```
'Name': ['John', 'Emma', 'Sophia', 'Mike']
'Age': [28, 22, 25, 30]
'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
```
Convert this dictionary into a Pandas DataFrame.

## Import the dataset using Pandas

### Download the data "listings.csv" from the below URL and put it in the notebook Directory
Data  - https://www.kaggle.com/jojoker/singapore-airbnb/data

### Reading Data into Pandas

### https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

pandas.read_csv(filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]],
                sep=',', delimiter=None, header='infer', names=None, index_col=None,
                usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True,
                dtype=None, engine=None, converters=None, true_values=None,
                false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0,
                nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False,
                skip_blank_lines=True, parse_dates=False, infer_datetime_format=False,
                keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True,
                iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.',
                lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None,
                comment=None, encoding=None, dialect=None, error_bad_lines=True, warn_bad_lines=True,
                delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)

In [ ]:
import pandas as pd
df = pd.read_csv('listings.csv') # Getting the data in the notebook

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
# Peak at the dataset - first overview of the data
df.head() # by default shows top 5 rows

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365
3,71609,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355

In [ ]:
df.tail(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
7897,38092051,New Small Room @Orchard/Somerset/Central Area,262337792,Herman,Central Region,River Valley,1.29482,103.83809,Private room,40,9,0,NaN,NaN,11,258
7898,38092142,Well connected 2 bedroom 2 bathroom apartment !,223622603,Tanya,Central Region,Rochor,1.30082,103.84956,Entire home/apt,200,2,0,NaN,NaN,4,347
7899,38094671,SMALL ROOM FOR ONE @SOMERSET/ORCHARD/CENTRAL AREA,262337792,Herman,Central Region,River Valley,1.29369,103.83768,Private room,33,7,0,NaN,NaN,11,359
7900,38102097,环境优雅的公寓,286260560,Bo,West Region,Bukit Batok,1.35654,103.76028,Private room,90,3,0,NaN,NaN,1,83
7901,38104971,2 PAX LOFT Close To Kent Ridge Park,278109833,Belle,Central Region,Queenstown,1.27973,103.78751,Entire home/apt,100,3,0,NaN,NaN,31,61
7902,38105126,Loft 2 pax near Haw Par / Pasir Panjang. Free Wifi,278109833,Belle,Central Region,Queenstown,1.27973,103.78751,Entire home/apt,100,3,0,NaN,NaN,31,61
7903,38108273,3bedroom luxury at Orchard,238891646,Neha,Central Region,Tanglin,1.29269,103.82623,Entire home/apt,550,6,0,NaN,NaN,34,365
7904,38109336,[ Farrer Park ] New City Fringe CBD Mins to MRT,281448565,Mindy,Central Region,Kallang,1.31286,103.85996,Private room,58,30,0,NaN,NaN,3,173
7905,38110493,Cheap Master Room in Central of Singapore,243835202,Huang,Central Region,River Valley,1.29543,103.83801,Private room,56,14,0,NaN,NaN,2,30
7906,38112762,Amazing room with private bathroom walk to Orchard,28788520,Terence,Central Region,River Valley,1.29672,103.83325,Private room,65,90,0,NaN,NaN,7,365

In [ ]:
pd.set_option('display.max_rows',100)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', None)

In [ ]:
#help(pd.set_option)

### INFO COMMAND

#### Dataset Info

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7907 non-null   int64
 1   name                            7905 non-null   object
 2   host_id                         7907 non-null   int64
 3   host_name                       7907 non-null   object
 4   neighbourhood_group             7907 non-null   object
 5   neighbourhood                   7907 non-null   object
 6   latitude                        7907 non-null   float64
 7   longitude                       7907 non-null   float64
 8   room_type                       7907 non-null   object
 9   price                           7907 non-null   int64
 10  minimum_nights                  7907 non-null   int64
 11  number_of_reviews               7907 non-null   int64
 12  last_review                     5149 non-null   object
 13  reviews_per_month               5149 non-null   float64
 14  calculated_host_listings_count  7907 non-null   int64
 15  availability_365                7907 non-null   int64
dtypes: float64(3), int64(7), object(6)
memory usage: 988.5+ KB

- Observations from the Info Command -

1. Total Number of Rows - 7907
2. Total Number of columns - 16
3. Non Null values Count , Missing Values
4. Data Types
5. Memory Usage of the Dataset
Add more

### describe()

- Descriptive Data Statistics

In [ ]:
df.describe(include = 'all')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
count,7.907000e+03,7905,7.907000e+03,7907,7907,7907,7907.000000,7907.000000,7907,7907.000000,7907.000000,7907.000000,5149,5149.000000,7907.000000,7907.000000
unique,NaN,7457,NaN,1833,5,43,NaN,NaN,3,NaN,NaN,NaN,1001,NaN,NaN,NaN
top,NaN,Luxury hostel with in-cabin locker - Single mixed,NaN,Jay,Central Region,Kallang,NaN,NaN,Entire home/apt,NaN,NaN,NaN,2019-08-12,NaN,NaN,NaN
freq,NaN,13,NaN,290,6309,1043,NaN,NaN,4132,NaN,NaN,NaN,152,NaN,NaN,NaN
mean,2.338862e+07,NaN,9.114481e+07,NaN,NaN,NaN,1.314192,103.848787,NaN,169.332996,17.510054,12.807386,NaN,1.043669,40.607689,208.726318
std,1.016416e+07,NaN,8.190910e+07,NaN,NaN,NaN,0.030577,0.043675,NaN,340.187599,42.094616,29.707746,NaN,1.285851,65.135253,146.120034
min,4.909100e+04,NaN,2.366600e+04,NaN,NaN,NaN,1.243870,103.646560,NaN,0.000000,1.000000,0.000000,NaN,0.010000,1.000000,0.000000
25%,1.582180e+07,NaN,2.305808e+07,NaN,NaN,NaN,1.295795,103.835825,NaN,65.000000,1.000000,0.000000,NaN,0.180000,2.000000,54.000000
50%,2.470627e+07,NaN,6.344891e+07,NaN,NaN,NaN,1.311030,103.849410,NaN,124.000000,3.000000,2.000000,NaN,0.550000,9.000000,260.000000
75%,3.234850e+07,NaN,1.553811e+08,NaN,NaN,NaN,1.322110,103.872535,NaN,199.000000,10.000000,10.000000,NaN,1.370000,48.000000,355.000000
max,3.811276e+07,NaN,2.885676e+08,NaN,NaN,NaN,1.454590,103.973420,NaN,10000.000000,1000.000000,323.000000,NaN,13.000000,274.000000,365.000000

- Observations from the df.describe() function

1. Count
2. Mean
3. Standard Deviation
4. Minimum
5. 25th percentile,
6. 50th percentile,
7. 75th Percentile
8. Maximum
9. It only by default diaplays stats for numerical columns ( Float and Int )

### .columns

Let us now understand column selection, addition, and deletion through examples.

In [ ]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group', 'neighbourhood', 'latitude',
       'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count', 'availability_365'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=7907, step=1)

In [ ]:
df.shape

(7907, 16)

##### Column Selection

We will understand this by selecting a column from the DataFrame.

In [ ]:
df.columns # Attribute of the dataframe - characteristic property of the dataframe

Index(['id',
       'name',
       'host_id',
       'host_name',
       'neighbourhood_group',
       'neighbourhood',
       'latitude',
       'longitude',
       'room_type',
       'price',
       'minimum_nights',
       'number_of_reviews',
       'last_review',
       'reviews_per_month',
       'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

## Access data in a dataframe

In [ ]:
# access single column
# access multiple columns
# access single row
# access multiple rows
# access a cell

In [ ]:
df.head(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365

In [ ]:
df["name"] # single column

0                        COZICOMFORT LONG TERM STAY ROOM 2
1                          Pleasant Room along Bukit Timah
2                                              COZICOMFORT
3                      Ensuite Room (Room 1 & 2) near EXPO
4                          B&B  Room 1 near Airport & EXPO
                               ...
7902    Loft 2 pax near Haw Par / Pasir Panjang. Free Wifi
7903                            3bedroom luxury at Orchard
7904       [ Farrer Park ] New City Fringe CBD Mins to MRT
7905             Cheap Master Room in Central of Singapore
7906    Amazing room with private bathroom walk to Orchard
Name: name, Length: 7907, dtype: object

In [ ]:
df[["name" , "neighbourhood"]] # Multiple columns

,name,neighbourhood
0,COZICOMFORT LONG TERM STAY ROOM 2,Woodlands
1,Pleasant Room along Bukit Timah,Bukit Timah
2,COZICOMFORT,Woodlands
3,Ensuite Room (Room 1 & 2) near EXPO,Tampines
4,B&B Room 1 near Airport & EXPO,Tampines
...,...,...
7902,Loft 2 pax near Haw Par / Pasir Panjang. Free Wifi,Queenstown
7903,3bedroom luxury at Orchard,Tanglin
7904,[ Farrer Park ] New City Fringe CBD Mins to MRT,Kallang
7905,Cheap Master Room in Central of Singapore,River Valley
7906,Amazing room with private bathroom walk to Orchard,River Valley

In [ ]:
df.loc[3]

id                                                              71609
name                              Ensuite Room (Room 1 & 2) near EXPO
host_id                                                        367042
host_name                                                     Belinda
neighbourhood_group                                       East Region
neighbourhood                                                Tampines
latitude                                                      1.34541
longitude                                                   103.95712
room_type                                                Private room
price                                                             206
minimum_nights                                                      1
number_of_reviews                                                  14
last_review                                                2019-08-11
reviews_per_month                                                0.15
calculated_host_listings_count                                      9
availability_365                                                  353
Name: 3, dtype: object

In [ ]:
df.loc[3:6] # end is inclusive

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
3,71609,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355
5,71903,Room 2-near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34702,103.96103,Private room,104,1,39,2019-08-15,0.38,9,346
6,71907,3rd level Jumbo room 5 near EXPO,367042,Belinda,East Region,Tampines,1.34348,103.96337,Private room,208,1,25,2019-07-25,0.25,9,172

In [ ]:
# row_index, column
df.loc[0, "price"]

83

In [ ]:
# df.loc[index_no, column_name] - Single Access

In [ ]:
df.loc[[4,7,8] , ["name","host_name"]]

,name,host_name
4,B&B Room 1 near Airport & EXPO,Belinda
7,"Long stay at The Breezy East ""Leopard""",Bianca
8,"Long stay at The Breezy East ""Plumeria""",Bianca

## Exercise

1. Accessing the 14th column
2. Accessing the 12th and 15th column
3. Acessing the 999th Row
4. Accessing the rows from 320:420
5. Access the data in the cell of 5th column , second row
5. Access the 10,11,15 th listing prices, neighbourhood, neighbourhood_group

## Drop Columns / Rows

In [ ]:
# Methods and not functions
# object.method()

df.drop(["name", "host_name"], axis = 1 )

,id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,266763,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,227796,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,266763,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365
3,71609,367042,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,367042,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7902,38105126,278109833,Central Region,Queenstown,1.27973,103.78751,Entire home/apt,100,3,0,NaN,NaN,31,61
7903,38108273,238891646,Central Region,Tanglin,1.29269,103.82623,Entire home/apt,550,6,0,NaN,NaN,34,365
7904,38109336,281448565,Central Region,Kallang,1.31286,103.85996,Private room,58,30,0,NaN,NaN,3,173
7905,38110493,243835202,Central Region,River Valley,1.29543,103.83801,Private room,56,14,0,NaN,NaN,2,30
7906,38112762,28788520,Central Region,River Valley,1.29672,103.83325,Private room,65,90,0,NaN,NaN,7,365

In [ ]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365
3,71609,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355

In [ ]:
df.drop([3,5,9], axis = 0)

## Renaming

In [ ]:
df.head(3)

,ID,NAME,HOST_ID,HOST_NAME,NEIGHBOURHOOD_GROUP,NEIGHBOURHOOD,LATITUDE,LONGITUDE,ROOM_TYPE,PRICE,MINIMUM_NIGHTS,NUMBER_OF_REVIEWS,LAST_REVIEW,REVIEWS_PER_MONTH,CALCULATED_HOST_LISTINGS_COUNT,AVAILABILITY_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365

In [ ]:
# HOST_ID -> HOST_IDENTITY
# df.rename(columns = {"HOST_ID" : "HOST_IDENTITY", "HOST_NAME":"HOST"})

In [ ]:
# df.rename({0 : "FIRST"}) # for renaming rows

In [ ]:
# df.set_index("HOST_ID")

In [ ]:
df.rename({"id" : "listing_id", "name" : "rename"} , axis = 1).head(5)

,listing_id,rename,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,73.953,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,72.171,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,61.479,6,20,2015-10-01,0.20,2,365
3,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,93.060,1,22,2019-07-28,0.22,9,355
4,71907,3rd level Jumbo room 5 near EXPO,367042,Belinda,East Region,Tampines,1.34348,103.96337,Private room,205.920,1,25,2019-07-25,0.25,9,172

In [ ]:
df.rename({0 : "ZERO"}, axis = 0).head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
ZERO,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,73.953,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,72.171,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,61.479,6,20,2015-10-01,0.20,2,365
3,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,93.060,1,22,2019-07-28,0.22,9,355
4,71907,3rd level Jumbo room 5 near EXPO,367042,Belinda,East Region,Tampines,1.34348,103.96337,Private room,205.920,1,25,2019-07-25,0.25,9,172

If we want to rename all columns at once, this helpful snippet of code creates a dictionary
with the old column names as keys and empty strings as values:

##### Selection by integer location

Rows can be selected by passing integer location to an iloc function.

##### How do you find the unique values inside a pandas column

In [ ]:
df.head(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,Puspendu,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,73.953,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,72.171,90,18,2014-12-26,0.28,1,365

In [ ]:
# Numerical - .min() , .max(), .mean() , .sum()

In [ ]:
# Categorical - nunique() , unique()

In [ ]:
df["neighbourhood_group"].value_counts(normalize = True)#.round(4)*100

Central Region       0.798203
West Region          0.068320
East Region          0.063892
North-East Region    0.043775
North Region         0.025810
Name: neighbourhood_group, dtype: float64

In [ ]:
df['neighbourhood_group'].value_counts()

Central Region       6309
West Region           540
East Region           505
North-East Region     346
North Region          204
Name: neighbourhood_group, dtype: int64

In [ ]:
df['neighbourhood_group'].value_counts().index

Index(['Central Region',
       'West Region',
       'East Region',
       'North-East Region',
       'North Region'],
      dtype='object')

In [ ]:
df['neighbourhood_group'].value_counts().values

array([6309,  540,  505,  346,  204])

### Finding the Minimum, Maximum, Sum, Average, and Count
pandas comes with some built-in methods for commonly used descriptive statistics. In addition, Pandas offers variance (var), standard deviation (std), kurtosis (kurt), skewness (skew), standard error of the mean(sem), mode (mode), median (median), and a number of others.

In [ ]:
# Calculate statistics
print('Maximum:', df['price'].max())
print('Minimum:', df['price'].min())
print('Mean:', df['price'].mean())
print('Sum:', df['price'].sum())
print('Count:', df['price'].count())

# Show counts
df.count()

Maximum: 9900.0
Minimum: 0.0
Mean: 167.6562870698381
Sum: 1325155.2930000003
Count: 7904

id                                7904
name                              7902
host_id                           7904
host_name                         7904
neighbourhood_group               7904
neighbourhood                     7904
latitude                          7904
longitude                         7904
room_type                         7904
price                             7904
minimum_nights                    7904
number_of_reviews                 7904
last_review                       5146
reviews_per_month                 5146
calculated_host_listings_count    7904
availability_365                  7904
dtype: int64

In [ ]:
df.describe().round(2).to_csv("data_description.csv")

### .to_csv()

In [ ]:
df.to_csv('exported_data.csv')

In [ ]:
df1 = pd.read_csv('exported_data.csv')
df1.head()

,listing_id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,calculated_host_listings_count,availability_365,discounted_price
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,2,365,66.4
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,1,365,64.8
2,50646,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,9,353,164.8
3,71903,Room 2-near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34702,103.96103,Private room,104,1,39,2019-08-15,9,346,83.2
4,71907,3rd level Jumbo room 5 near EXPO,367042,Belinda,East Region,Tampines,1.34348,103.96337,Private room,208,1,25,2019-07-25,9,172,166.4

In [ ]:
df.to_csv('exported_data.csv', index = False)

In [ ]:
df2=pd.read_csv('exported_data.csv')
df2.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365
3,71609,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355