# Missing Values
A missing value refers to the absence of a data entry in a dataset where a value is expected. This can occur due to various reasons, such as data entry errors, incomplete data collection, or intentional omissions. Missing values can impact data analysis and machine learning models, requiring strategies like imputation, deletion, or interpolation to handle them effectively.

* Missing values might be the most undesired values in data science. We definitely do not want to have them. However, they are always around.
* Since it is not reasonable to ignore missing values, we need to find ways to handle them efficiently and properly.
* In this Notebook, we will learn different methods to make the missing values go away without causing a lot of trouble. However, which method fits best to a particular situation depends on the data and task.

## Detecting Missing Values

Before handling missing values, we need to detect them. We use Pandas to check for missing values in a dataset.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({
    "Date": pd.date_range(start="2022-01-01",periods=10,freq="D"),
    "Item": np.random.randint(1010,1020,size=10),
    "Measure_1": np.random.randint(1,10,size=10),
    "Measure_2": np.random.random(10).round(2),
    "Measure_3": np.random.random(10).round(2),
    "Measure_4": np.random.randn(10)
})

In [ ]:
df

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2022-01-01  1017          1       0.75       0.59  -0.324397
1 2022-01-02  1012          8       0.96       0.46  -0.137365
2 2022-01-03  1015          2       0.50       0.41  -0.389586
3 2022-01-04  1010          1       0.28       0.36  -0.548285
4 2022-01-05  1013          9       0.59       0.33  -0.751930
5 2022-01-06  1013          7       0.33       0.03   0.654156
6 2022-01-07  1016          5       0.22       0.13   0.903751
7 2022-01-08  1019          5       0.38       0.41   1.795945
8 2022-01-09  1017          2       0.89       0.04  -0.583570
9 2022-01-10  1016          2       0.59       0.15  -0.124610

The next step is to add the missing values. We will use the loc method to select the row and column combinations and make them equal to “np.nan” which is one of the standard missing value representations.

In [ ]:
df.loc[[2,7],"Item"] = np.nan
df.loc[[1,6,7],"Measure_1"] = np.nan
df.loc[[4,5,7],"Measure_2"] = np.nan
df.loc[[7],"Measure_3"] = np.nan
df.loc[[7,9],"Measure_4"] = np.nan

In [ ]:
df

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397
1 2022-01-02  1012.0        NaN       0.96       0.46  -0.137365
2 2022-01-03     NaN        2.0       0.50       0.41  -0.389586
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285
4 2022-01-05  1013.0        9.0        NaN       0.33  -0.751930
5 2022-01-06  1013.0        7.0        NaN       0.03   0.654156
6 2022-01-07  1016.0        NaN       0.22       0.13   0.903751
7 2022-01-08     NaN        NaN        NaN        NaN        NaN
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570
9 2022-01-10  1016.0        2.0       0.59       0.15        NaN

- Ok in this case the data is very low so we can see it in naked eye what if there is too many data how can we detect it

In [ ]:
# Checking for missing values
print("\nMissing Values Count:\n", df.isnull().sum())  # Count of missing values per column

Missing Values Count:
 Date         0
Item         2
Measure_1    3
Measure_2    3
Measure_3    1
Measure_4    2
dtype: int64

## Drop rows or columns that have a missing value
* One option is to drop the rows or columns that contain a missing value.

In [ ]:
df

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397
1 2022-01-02  1012.0        NaN       0.96       0.46  -0.137365
2 2022-01-03     NaN        2.0       0.50       0.41  -0.389586
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285
4 2022-01-05  1013.0        9.0        NaN       0.33  -0.751930
5 2022-01-06  1013.0        7.0        NaN       0.03   0.654156
6 2022-01-07  1016.0        NaN       0.22       0.13   0.903751
7 2022-01-08     NaN        NaN        NaN        NaN        NaN
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570
9 2022-01-10  1016.0        2.0       0.59       0.15        NaN

* Only the date column does not have any missing values.

In [ ]:
df.dropna()

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570

* With the default parameter values, the dropna function drops the rows that contain any missing value.
* There is only three row in the data frame that does not have any missing values.
* We can also choose to drop columns that have at least one missing value by using the axis parameter.

## Drop rows or columns that only have missing values
Another situation is to have a column or row that is full of missing values. Such columns or rows are useless so we can drop them.
The dropna function can be used for this as well. We just need to change the value of how parameter.

In [ ]:
# Add a column with missing value
df['null_column'] = np.nan
df

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4  null_column
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397          NaN
1 2022-01-02  1012.0        NaN       0.96       0.46  -0.137365          NaN
2 2022-01-03     NaN        2.0       0.50       0.41  -0.389586          NaN
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285          NaN
4 2022-01-05  1013.0        9.0        NaN       0.33  -0.751930          NaN
5 2022-01-06  1013.0        7.0        NaN       0.03   0.654156          NaN
6 2022-01-07  1016.0        NaN       0.22       0.13   0.903751          NaN
7 2022-01-08     NaN        NaN        NaN        NaN        NaN          NaN
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570          NaN
9 2022-01-10  1016.0        2.0       0.59       0.15        NaN          NaN

In [ ]:
df.dropna(how="all")

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4  null_column
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397          NaN
1 2022-01-02  1012.0        NaN       0.96       0.46  -0.137365          NaN
2 2022-01-03     NaN        2.0       0.50       0.41  -0.389586          NaN
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285          NaN
4 2022-01-05  1013.0        9.0        NaN       0.33  -0.751930          NaN
5 2022-01-06  1013.0        7.0        NaN       0.03   0.654156          NaN
6 2022-01-07  1016.0        NaN       0.22       0.13   0.903751          NaN
7 2022-01-08     NaN        NaN        NaN        NaN        NaN          NaN
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570          NaN
9 2022-01-10  1016.0        2.0       0.59       0.15        NaN          NaN

* Since the data frame does not have a row full of missing values, no row has been dropped.

## Drop rows or columns based on a threshold value
Dropping based on “any” or “all” is not always the best option. We sometimes need to drop rows or columns with “lots of” or “some” missing values.
We cannot assign such expressions to the how parameter but Pandas gives us a more accurate way which is the thresh parameter.
For instance, “thresh=4” means that the rows that have at least 4 non-missing values will be kept. The other ones will be dropped.
Our data frame has 6 columns so the rows that have 3 or more missing values will be dropped.

In [ ]:
df.dropna(thresh=4)

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4  null_column
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397          NaN
1 2022-01-02  1012.0        NaN       0.96       0.46  -0.137365          NaN
2 2022-01-03     NaN        2.0       0.50       0.41  -0.389586          NaN
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285          NaN
4 2022-01-05  1013.0        9.0        NaN       0.33  -0.751930          NaN
5 2022-01-06  1013.0        7.0        NaN       0.03   0.654156          NaN
6 2022-01-07  1016.0        NaN       0.22       0.13   0.903751          NaN
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570          NaN
9 2022-01-10  1016.0        2.0       0.59       0.15        NaN          NaN

Only the seventh row had more than 4 missing values so it was the only one dropped.

## Drop based on a particular subset of columns
We can take only some of the columns into consideration when dropping columns.
The subset parameter of the dropna function is used for this task. For instance, we can drop the rows that have a missing value in measure_1 or measure_2 columns as follows:

In [ ]:
df.dropna(subset=["Measure_1","Measure_2"])

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4  null_column
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397          NaN
2 2022-01-03     NaN        2.0       0.50       0.41  -0.389586          NaN
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285          NaN
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570          NaN
9 2022-01-10  1016.0        2.0       0.59       0.15        NaN          NaN

* Dropping is not the only option. In some cases, we may choose to fill missing values instead of dropping them.
* In fact, the filling might be a better option since data means value. How to fill the missing values, of course, depend on the structure of data and the task.

## Treat Missing Values

So far we have taken the critical step of dropping rows with missing values, ensuring that our dataset remains complete. This was a straightforward approach that helped us eliminate the immediate concern of incomplete data, but now, we face the next challenge: how can we handle the missing values in a more thoughtful way?

Dropping missing values might not always be the best solution. While it works in cases where the missing data is minimal, we lose valuable information when we discard entire rows. In fact, if a dataset has a significant number of missing values, dropping those rows could lead to biases or distort the underlying trends in the data.

To tackle this, we need a more robust way of handling missing data. Instead of just dropping rows, we can treat the missing values by filling them in with more informed methods. Let’s explore some options.

## Fill with a constant value
We can choose a constant value to be used as a replacement for the missing values.
If we just give one constant value to the fillna function, it will replace all the missing values in the data frame with that value.
A more reasonable method is to determine separate constant values for different columns. We can write them in a dictionary and pass it to the values parameter.

In [ ]:
df.fillna(value=0)

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4  null_column
0 2022-01-01  1017.0        1.0       0.75       0.59  -0.324397          0.0
1 2022-01-02  1012.0        0.0       0.96       0.46  -0.137365          0.0
2 2022-01-03     0.0        2.0       0.50       0.41  -0.389586          0.0
3 2022-01-04  1010.0        1.0       0.28       0.36  -0.548285          0.0
4 2022-01-05  1013.0        9.0       0.00       0.33  -0.751930          0.0
5 2022-01-06  1013.0        7.0       0.00       0.03   0.654156          0.0
6 2022-01-07  1016.0        0.0       0.22       0.13   0.903751          0.0
7 2022-01-08     0.0        0.0       0.00       0.00   0.000000          0.0
8 2022-01-09  1017.0        2.0       0.89       0.04  -0.583570          0.0
9 2022-01-10  1016.0        2.0       0.59       0.15   0.000000          0.0

- But this is wrong since each column in the dataset may contain different types of information, whether numerical, categorical, or even time-based.

In [ ]:
values = {"Item":1016, "Measure_1":0}

df.fillna(value = values)

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4  null_column
0 2022-01-01  1014.0        7.0       0.77       0.87  -0.108794          NaN
1 2022-01-02  1017.0        0.0       0.44       0.25   0.186370          NaN
2 2022-01-03  1016.0        3.0       0.55       0.18  -0.678439          NaN
3 2022-01-04  1011.0        8.0       0.37       0.01   0.669145          NaN
4 2022-01-05  1018.0        3.0        NaN       0.51   0.620625          NaN
5 2022-01-06  1016.0        5.0        NaN       0.74   0.826805          NaN
6 2022-01-07  1011.0        0.0        NaN       0.93   1.012412          NaN
7 2022-01-08  1016.0        0.0        NaN        NaN        NaN          NaN
8 2022-01-09  1011.0        3.0       0.28       0.21   1.155548          NaN
9 2022-01-10  1010.0        4.0       0.95       0.70        NaN          NaN

* The missing values in the item column are replaced with 1016 and the ones in the measure_1 column are replaced with 0.

- Again there is a problem how should you kown which value is correct to treat it, As a result, the way we handle missing values should be tailored to each specific column.

**For numerical columns, we might:**
- Use mean imputation to fill in missing values, but only if the data is approximately normally distributed.
- Use median imputation when the data is skewed or contains outliers, to avoid distorting the overall distribution.

**For categorical columns, we can:**
- Use mode imputation (the most frequent value) to fill in missing categories, ensuring that the general trend of the dataset is preserved.

## Fill with an aggregated value
Another option is to use an aggregated value such as mean, median, or mode.
The following line of code replaces the missing values in the measure 2 column with the average value of this column.

In [ ]:
df["Measure_2"].fillna(df["Measure_2"].mean())

0    0.77
1    0.44
2    0.55
3    0.37
4    0.56
5    0.56
6    0.56
7    0.56
8    0.28
9    0.95
Name: Measure_2, dtype: float64

## Replace with the previous or next value
It is possible to replace the missing values in a column with the previous or next value in that column.
This method might come in handy when working with time-series data. Consider you have a data frame that contains the daily temperature measurement and the temperate in one day is missing. The optimal solution would be to use the temperature in the next or previous day.
The method parameter of the fillna function is used for performing this task.

In [ ]:
df.fillna(method='ffill')

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4  null_column
0 2022-01-01  1014.0        7.0       0.77       0.87  -0.108794          NaN
1 2022-01-02  1017.0        NaN       0.44       0.25   0.186370          NaN
2 2022-01-03     NaN        3.0       0.55       0.18  -0.678439          NaN
3 2022-01-04  1011.0        8.0       0.37       0.01   0.669145          NaN
4 2022-01-05  1018.0        3.0        NaN       0.51   0.620625          NaN
5 2022-01-06  1016.0        5.0        NaN       0.74   0.826805          NaN
6 2022-01-07  1011.0        NaN        NaN       0.93   1.012412          NaN
7 2022-01-08     NaN        NaN        NaN        NaN        NaN          NaN
8 2022-01-09  1011.0        3.0       0.28       0.21   1.155548          NaN
9 2022-01-10  1010.0        4.0       0.95       0.70        NaN          NaN

* The “bfill” fills the missing values backward so they are replaced with the next value.
Take a look at the last column. The missing values are replaced up to the first row. This may not be suitable for some cases.
Thankfully, we can limit the number of missing values replaced with this method. If we set the limit parameter as 1, then a missing value can only be replaced with its next value. The second or third following value will not be used for replacement.

In [ ]:
df.fillna(method='bfill', limit=1)

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2022-01-01  1014.0        6.0       0.25       0.41  -1.865194
1 2022-01-02  1018.0        9.0       0.80       0.78   1.088583
2 2022-01-03  1012.0        9.0       0.50       0.88   0.008982
3 2022-01-04  1012.0        4.0       0.20       0.21   1.811965
4 2022-01-05  1013.0        5.0        NaN       0.46   0.662545
5 2022-01-06  1013.0        4.0       0.69       0.83   0.146111
6 2022-01-07  1010.0        NaN       0.69       0.05   1.212649
7 2022-01-08  1015.0        8.0       0.45       0.02  -0.251755
8 2022-01-09  1015.0        8.0       0.45       0.02  -0.251755
9 2022-01-10  1016.0        9.0       0.92       0.37        NaN

# Exercise
You are a data analyst working with an HR department. The company maintains a dataset of employees, which includes their name, age, city, and salary. However, some records have missing values due to incomplete data collection. Your goal is to clean the dataset by detecting and handling missing values, which will allow the company to use the data for reporting and analysis.

## Create Dataset
Create the dataset using this code:
```
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, np.nan, 30, 22, np.nan],
    "City": ["New York", "Los Angeles", np.nan, "Chicago", "Miami"],
    "Salary": [50000, 60000, 55000, np.nan, 45000]
}
df_simple = pd.DataFrame(data)
```
1. **Question 1**: Use pandas to check for missing values in the dataset.
    - How many missing values are there in each column?
    - What percentage of the data is missing for each column?

2. **Question 2**:
    - For the `Age` and `Salary` columns, fill the missing values with the **mean** of the respective column.
    - For the `City` column, fill the missing values with the **mode** (most frequent value) of the column.

3. **Question 3**:
    - Drop the rows with missing values from the dataset. What happens to the dataset after deleting the rows with missing data?